#ifndef ROMEA_CORE_GPS_NMEA_NMEAMODEINDICATOR_HPP_
#define ROMEA_CORE_GPS_NMEA_NMEAMODEINDICATOR_HPP_

// std
#include <string>

namespace romea
{

enum class ModeIndicator
{
  NO_FIX_MODE,
  GPS_MODE,
  DGPD_MODE,
  PRECISE_MODE,
  RTK_MODE,
  FLOAT_RTK_MODE,
  ESTIMATED_MODE,
  MANUAL_MODE,
  SIMULATION_MODE
};

}  // namespace romea

#endif  // ROMEA_CORE_GPS_NMEA_NMEAMODEINDICATOR_HPP_
